server:
  port: 8082
  servlet:
    context-path: /rest-api-admin-server
  application:
    name: rest-api-admin-server
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always