server:
  port: 8001
  servlet:
    context-path: /rest-api-admin-server
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: rest-api-admin-server
  jmx:
    default-domain: /rest-api-admin-server